### ISSUE TITLE
Convert compound name to database ID

### ISSUE THREAD

**Issue by hh1985** [computational-metabolomics/msPurity#77]
Hi,

Is there any recommended way to convert the search results of msPurity to public database ID, such as HMDB, pubchem and so on.

Thanks,

-hh1985

**Comment by Tomnl** [comment]
Hi @hh1985 ,

Additional compound details are in the SQLite database. See below for how to extract that information


```
q_dbPth <- system.file("extdata", "tests", "db",
                       "createDatabase_example.sqlite", package="msPurity")

# Run spectral matching with "updateDb" and "copyDb" set to True
# Can be run with "copyDb" set to False and write to the existing database (useful if you don't want to create multiple sqlite databases)
result <- spectralMatching(q_dbPth,  
                                          q_xcmsGroups = c(12, 27),
                                          cores=1,
                                          updateDb = T,
                                          copyDb = T,  
                                          l_accessions=c('CCMSLIB00000577898','CE000616'))


# connect to the sqlite database
con <- DBI::dbConnect(RSQLite::SQLite(), result$q_dbPth)

# This will give you table of all the relevant compounds
metab_compound <- DBI::dbGetQuery(con, 'SELECT * FROM metab_compound')
print(metab_compound)

# But if use some SQL joins you add some extra columns onto the matching standard output
additional_compound_details <- DBI::dbGetQuery(con, 'SELECT xm.*,
                                               mc.pubchem_id,
                                               mc.exact_mass,
                                               mc.molecular_formula,
                                               mc.smiles
                                               FROM xcms_match AS xm 
                                              LEFT JOIN metab_compound as mc ON mc.inchikey_id=xm.inchikey')
print(additional_compound_details)

# Alternatively you can connect directly to the library SQLite database and extract the compound details from there

``

**Comment by hh1985** [comment]
@Tomnl Thanks for the information.  I can successfully extract the pubchem ID now.  One additional question which may be unrelated to the current issue: in my data (serum),  ~ 2300 features identified in XCMS. However, only 87 features were linked to MS/MS annotation.  Is this normal?  What should I do to increase the identification rate?

**Comment by Tomnl** [comment]
The number of linked features to MS/MS for DDA will be low in many cases. And will depend on various factors including how the data was processed, how the data was collected and how busy the spectra is. 

One key aspect for the standard msPurity settings is that it relies on having sufficient MS1 data in the DDA file that XCMS can pick a feature (and successfully group with other files).

However, if you have a typical setup where you have additional files with DDA data and you are grouping with other MS1 only data files. If you reduce the minfrac in XCMS so that grouping only requires one file (e.g. set to 0.01, or some other low value) - you will see more features linked to MS/MS (but you will also increase the total number of features in the dataset!).

**Comment by hh1985** [comment]
@Tomnl I will try what you suggested. Thanks!
