### ISSUE TITLE
Correction for the reverse dot product cosine (rpdc) in the spectralMatching module

### ISSUE THREAD

**Issue by xiaodfeng** [computational-metabolomics/msPurity#78]
In the spectralMatching module, the codes for calculating the reverse dot product cosine (rpdc) is:
`  rl <- aligned$l[!aligned$q==0]
rq <- aligned$q[!aligned$q==0]
rdpcOut <- dpc(rq, rl)`
Above codes remove the library peaks that do not match in the query spectra. According to the definition of [reverse library search](https://kermitmurray.com/msterms/index.php?title=Reverse_library_search). We should remove the query peaks that do not match in the library spectra.My correction for the reverse dot product cosine (rpdc) is:
`  rl <- aligned$l[!aligned$l==0]
rq <- aligned$q[!aligned$l==0]
rdpcOut <- dpc(rq, rl)`

Further discussion can be accessed [here](https://github.com/rformassspectrometry/Spectra/issues/46)

**Comment by Tomnl** [comment]
Thanks @xiaodfeng for spotting this. 

Your proposal seems like a correct way to implement for the rdpc function and seems to be more in line with other software like MS-DIAL as well. 

I still think having a spectral match that removes peaks in the library that do match in the query could be useful (say if the library data is noisy) but not sure if it that would still count as reverse dot product ... perhaps it would be called reverse query search?

Anyway.. I will change rdpc function to your suggestion so that is included in the next Bioconductor release.

Thanks

**Comment by xiaodfeng** [comment]
Thank you for maintaining this package. I do think the method of removing peaks in the library make sense. We just do not have a proper name for it. The reverse library search assume the data quality of the library is high, namely less noisy. But this is not always the case for the experimental data stored in the library. The first paper about reverse library search is [here](http://dx.doi.org/10.1021/ac60351a028)

**Comment by Tomnl** [comment]
I have made the changes in github and pushed to both dev and stable of bioconductor. 

If it is OK with you, I will close this issue now

**Comment by xiaodfeng** [comment]
Thank you for maintaining this package. Feel free to close it.
